name: fleet

problem:
  input_effort: 1.0
  fleet_preference: 0.0 # -1.0
  agent_preference: 0.0 # 0.05
  n_robots: 5
  n_states: 2 # NOTE: at the moment, only 2D is supported
  horizon: 25 # plan over horizon * h seconds
  h: 0.25 # time step of the optimization, the control is finer
  # TODO: if gravity is not zero, it should affect also the dynamics
  gravity: [0, 0] # generalized gravity vector # -9.81
  constraints:
    working_space:
      # 10x10x10 working space, as in FMA
      lower_bound: -5.0
      upper_bound: 5.0
    velocity:
      # m/s
      lower_bound: -20.0
      upper_bound: 20.0
    acceleration:
      # m/s^2
      lower_bound: -5.0
      upper_bound: 5.0
    jerk:
      # m/s^3
      lower_bound: -1.5
      upper_bound: 1.5

dataset:
  batch_size: 512
  size: -1 # to generate indefinitely for training
  val_size: 1024
  test_size: 1024