problem:
  n_robots: 1
  n_states: 2
  horizon: 10 # plan over 10 seconds
  h: 1 # time step of the optimization, the control is finer
  # TODO: if gravity is not zero, it should affect also the dynamics
  gravity: [0, 0] # generalized gravity vector # -9.81
  constraints:
    working_space:
      # 10x10x10 working space, as in FMA
      lower_bound: -5.0
      upper_bound: 5.0
    velocity:
      # m/s
      lower_bound: -10.0
      upper_bound: 10.0
    acceleration:
      # m/s^2
      lower_bound: -10.0
      upper_bound: 10.0
    jerk:
      # m/s^3
      lower_bound: -20.0
      upper_bound: 20.0

dataset:
  batch_size: 512
  size: 2048 # -1 to generate indefinitely for training
  val_size: 512
  test_size: 512