problem:
  n_robots: 2
  n_states: 3
  horizon: 2
  h: 0.1
  gravity: [0, 0, -9.81] # generalized gravity vector

dataset:
  batch_size: 32
  size: 2048 # -1 to generate indefinitely for training
  val_size: 512
  test_size: 512