name: hcnn
unroll: False
fpi: False
autotuning: False
equilibration: False
n_iter_train: 200
n_iter_test: 1000
n_iter_bwd: 100
sigma: 0.1
omega: 1.7
learning_rate: 0.001
features: [64, 64]
activation: relu
seed: 0