model_name: hcnn
unroll: False
fpi: False
autotuning: False
equilibration: False
n_iter_train: 100
n_iter_test: 1000
n_iter_bwd: 10
sigma: 1.0
omega: 1.7
learning_rate: 0.001
features: [64, 64]
activation: softplus
seed: 0
collision_penalty_fn: collision_penalty_log
collision_penalty: 10